on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      - run: Rscript -e 'rmarkdown::render("web_report.Rmd")'
      - name: Upload results
        uses: actions/upload-artifact@main
        with:
          name: results
          path: web_report.html
