on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
jobs:
  render:
    name: Render Rmarkdown file
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - name: Print wd1
        run: Rscript -e 'getwd()'
    
      - name: Install packages
        run: |
          install.packages('remotes')
          remotes::install_cran("here")
          remotes::install_cran("googlesheets4")
          remotes::install_cran("janitor")
          remotes::install_cran("gt")
          remotes::install_github("UrbanInstitute/urbnthemes")
        shell: Rscript {0}

      - name: Print wd2
        run: Rscript -e 'getwd()'
        
      - name: go back one dir
        run: cd ../

      - name: Print wd3
        run: Rscript -e 'getwd()'
        
      - name: List files of folder
        run: Rscript -e 'list.files("/__w/texas-fundraising-urban/")'
        
      # - name: Render rmarkdown
      #   run: Rscript -e 'rmarkdown::render("web_report.Rmd")'
      #   
      #   
      # - name: Push commits
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "Render Rmd (GH Actions)"
      #     git push
      # 
