on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
jobs:
  render:
    name: Render Rmarkdown file
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      
      - name: Install packages
        run: |
          install.packages('remotes')
          remotes::install_cran("here")
          remotes::install_cran("googlesheets4")
          remotes::install_cran("janitor")
          remotes::install_cran("gt")
          remotes::install_github("UrbanInstitute/urbnthemes")
        shell: Rscript {0}

      - name: Render rmarkdown
        run: Rscript -e 'rmarkdown::render("web_report.Rmd")'
      
      - uses: EndBug/add-and-commit@v7.0.0